### ISSUE TITLE
Hints for mixins

### ISSUE THREAD

**Issue by dularion** [sprintr/brackets-sass-code-hints#3]
Is it at all possible to add mixin-hint functionality to this extension? 
I feel that mixins are a big part of scss, and other IDEs are able to show me the mixins as hints while typing them. Keyword would be @include, and it looks for all @mixin commands in all scss files to find hintable snippets.

![screen shot 2015-03-14 at 16 32 39](https://cloud.githubusercontent.com/assets/936076/6652205/c14bf6de-ca67-11e4-8137-3fb642e0972e.png)

in the screenshot you can see an example, where i include my mixin file and try to use the vendor-property mixin, without any hints right now..  below you find the mixin definition: 

````
@mixin vendor-property($property, $value) {
    @each $vendor in ('-moz-', '-webkit-', '-o-', '-ms-', '') {
        #{$vendor}#{$property}: #{$value};
    }
}
````

**Comment by sprintr** [comment]
This extension was written to provide code hints for `.sass` documents since brackets don't provide hinting in `.sass`.

I may write up another extension that provides hinting mixins in scss and sass too.

**Comment by dularion** [comment]
Actually, I am working on a fix for this right now. You'll receive a pull request shortly.
